### PR TITLE
[WIP] Support this gem 

### PR DESCRIPTION
**Pull request by Nittarab**
Hi, I will run some test and upgrade this gem in order to keep up to date the compatibility.

@lowjoel  I will maintain this project, let me know I can use your repository (there are some issue I will work on) 
if you prefer I can create a fork and when the gem is ready, you can just write "Deprecated new one"
I read that you were working on a new release, can you push the code in a new branch? 

If there are other users that will contribute, just comment this pull request

### CODE REVIEW

**Comment by lowjoel** [comment]
Hm. I think it's best for you to write _yet another_ fork. I was hoping to use this but my day job has moved away from using Rails, and I'm struggling to find time to maintain this.

This makes permissions with RubyGems etc. easier, too. I'll update the readme.

**Comment by Nittarab** [comment]
Thank you, I will work on this in the next weeks. And update you when the update is ready.

**Comment by deepakmahakale** [comment]
Hi @lowjoel  @Nittarab anything on this yet?

I badly need the fix for `on: create` as it's breaking and don't want to change the ref to yet another fork

**Comment by Nittarab** [comment]
Hi @deepakmahakale  I dont't have had the time to work on it, but I will do it asap

**Pull request closed without merging**
