### PR TITLE
Updated Travis build matrix.

### PR DESCRIPTION
**Pull request by saghaulor**

### CODE REVIEW

**Comment by saghaulor** [comment]
@lowjoel Please consider merging to include MRI v2.3 in the Travis builds.

**Comment by lowjoel** [comment]
@saghaulor I kept the specific patch version of Ruby because Travis uses old versions of 2.0 2.1 and 2.2 otherwise. Please use the latest patch version, do not drop them.

**Comment by saghaulor** [comment]
@lowjoel Thanks for the feedback. I assumed that by specifying a generic version, it would pull the latest. Obviously I was mistaken. I'll fix the PR.

**Comment by lowjoel** [comment]
Awesome, thanks!

**Pull request merged**
